export declare const Icon: import("atomico/types/dom").Atomico<{
    type: "search" | "attachment" | "file" | "closed" | "left" | "right" | "copy" | "audio" | "menu" | "textarea" | "video" | "circle" | "image" | "switch" | "drag" | "home" | "options" | "up" | "alert" | "zero" | "calendar" | "check" | "logo" | "down" | "avatar" | "lock" | "config" | "dash" | "plus" | "asterisk" | "eye" | "love" | "clock" | "profile" | "dragX" | "dragXToLeft" | "dragXToRight" | "checkbox" | "dropdown";
    icons: {
        logo: Element;
        check: Element;
        down: Element;
        up: Element;
        left: Element;
        right: Element;
        alert: Element;
        closed: Element;
        avatar: Element;
        menu: Element;
        lock: Element;
        video: Element;
        image: Element;
        audio: Element;
        config: Element;
        options: Element;
        copy: Element;
        dash: Element;
        plus: Element;
        asterisk: Element;
        eye: Element;
        search: Element;
        file: Element;
        drag: Element;
        home: Element;
        love: Element;
        clock: Element;
        profile: Element;
        dragX: Element;
        dragXToLeft: Element;
        dragXToRight: Element;
        checkbox: Element;
        circle: Element;
        dropdown: Element;
        switch: Element;
        textarea: Element;
        zero: Element;
        attachment: Element;
        calendar: Element;
    };
} & {
    color?: string;
    size?: string;
}, {
    type: "search" | "attachment" | "file" | "closed" | "left" | "right" | "copy" | "audio" | "menu" | "textarea" | "video" | "circle" | "image" | "switch" | "drag" | "home" | "options" | "up" | "alert" | "zero" | "calendar" | "check" | "logo" | "down" | "avatar" | "lock" | "config" | "dash" | "plus" | "asterisk" | "eye" | "love" | "clock" | "profile" | "dragX" | "dragXToLeft" | "dragXToRight" | "checkbox" | "dropdown";
    icons: {
        logo: Element;
        check: Element;
        down: Element;
        up: Element;
        left: Element;
        right: Element;
        alert: Element;
        closed: Element;
        avatar: Element;
        menu: Element;
        lock: Element;
        video: Element;
        image: Element;
        audio: Element;
        config: Element;
        options: Element;
        copy: Element;
        dash: Element;
        plus: Element;
        asterisk: Element;
        eye: Element;
        search: Element;
        file: Element;
        drag: Element;
        home: Element;
        love: Element;
        clock: Element;
        profile: Element;
        dragX: Element;
        dragXToLeft: Element;
        dragXToRight: Element;
        checkbox: Element;
        circle: Element;
        dropdown: Element;
        switch: Element;
        textarea: Element;
        zero: Element;
        attachment: Element;
        calendar: Element;
    };
} & {
    color?: string;
    size?: string;
}, {
    new (): HTMLElement;
    prototype: HTMLElement;
}>;
